#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SITE = process.env.SITE_URL ?? "https://khanalagao.com";
const API = process.env.BLOG_API_URL ?? `${SITE}/api/marketing/blog/posts?pageSize=1000`;
const SITEMAP_PATH = resolve(__dirname, "..", "public", "sitemap.xml");
const BEGIN = "<!-- BEGIN BLOG POSTS (auto-generated by scripts/generate-sitemap.mjs) -->";
const END = "<!-- END BLOG POSTS -->";

async function fetchSlugs() {
  try {
    const res = await fetch(API, { headers: { accept: "application/json" } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    const posts = Array.isArray(data) ? data : data.posts ?? data.items ?? data.data ?? [];
    if (!Array.isArray(posts) || posts.length === 0) {
      console.warn(`[sitemap] No blog posts returned from ${API}; keeping existing entries.`);
      return null;
    }
    return posts
      .filter((p) => p && p.slug)
      .map((p) => {
        const ts = p.publishedAt ?? p.published_at ?? p.updatedAt ?? p.updated_at ?? null;
        const lastmod = ts ? new Date(ts).toISOString().slice(0, 10) : new Date().toISOString().slice(0, 10);
        return { slug: p.slug, lastmod };
      });
  } catch (err) {
    console.warn(`[sitemap] Could not fetch ${API}: ${err.message}. Keeping existing entries.`);
    return null;
  }
}

function renderBlock(posts) {
  const lines = posts.map(
    (p) =>
      `  <url><loc>${SITE}/blog/${p.slug}</loc><lastmod>${p.lastmod}</lastmod><changefreq>monthly</changefreq><priority>0.6</priority></url>`
  );
  return [BEGIN, ...lines, "  " + END].join("\n  ");
}

async function main() {
  const posts = await fetchSlugs();
  if (!posts) return;
  const xml = readFileSync(SITEMAP_PATH, "utf8");
  const beginIdx = xml.indexOf(BEGIN);
  const endIdx = xml.indexOf(END);
  if (beginIdx === -1 || endIdx === -1) {
    console.error("[sitemap] Markers not found in sitemap.xml; aborting to avoid corruption.");
    process.exit(1);
  }
  const before = xml.slice(0, beginIdx);
  const after = xml.slice(endIdx + END.length);
  writeFileSync(SITEMAP_PATH, before + renderBlock(posts) + after);
  console.log(`[sitemap] Wrote ${posts.length} blog URL(s) to ${SITEMAP_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
