/**
 * Curated default catalog of Indian dishes for the stock food image
 * library. Image URLs point at Wikimedia Commons (royalty-free,
 * hot-linkable). Super-admins can edit, deactivate, or extend this
 * catalog from the admin UI — the seeder only adds missing slugs,
 * it never overwrites existing rows.
 *
 * Adding a new dish here will register it on the next API boot.
 */

export interface StockFoodSeedEntry {
  /** Optional explicit slug; defaults to slugified name. */
  slug?: string;
  name: string;
  cuisine?: string;
  category?: string;
  imageUrl: string;
  thumbnailUrl?: string;
  aliases?: string[];
  tags?: string[];
  isVeg?: boolean;
  sortOrder?: number;
  attribution?: string;
  /** Extended dietary classification: veg | non-veg | vegan | jain | egg */
  dietaryType?: string;
  /** Meal placement: starter | main | dessert | drink | snack | breakfast | bread | rice | side */
  mealType?: string;
  /** Spice level 0..3 (0=mild, 3=fiery). */
  spiceLevel?: number;
  /** If true, surfaced as a featured pick in the tenant picker. */
  isFeatured?: boolean;
}

const W = "https://upload.wikimedia.org/wikipedia/commons";

export const STOCK_FOOD_IMAGE_SEED: StockFoodSeedEntry[] = [
  // ─── North Indian — Veg curries ────────────────────────────────
  {
    name: "Paneer Tikka",
    cuisine: "north-indian", category: "starter", isVeg: true,
    imageUrl: `${W}/thumb/3/30/Paneer_Tikka_at_Velleeswarar_Sannathi_Restaurant%2C_Chennai.jpg/800px-Paneer_Tikka_at_Velleeswarar_Sannathi_Restaurant%2C_Chennai.jpg`,
    aliases: ["tandoori paneer", "paneer tikka kabab"],
    tags: ["tandoori", "starter", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Palak Paneer",
    cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/c/c2/Palak_Paneer_with_naan.jpg/800px-Palak_Paneer_with_naan.jpg`,
    aliases: ["saag paneer", "spinach paneer"],
    tags: ["curry", "spinach"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Paneer Butter Masala",
    cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/f/f0/Paneer_makhani.JPG/800px-Paneer_makhani.JPG`,
    aliases: ["paneer makhani", "butter paneer"],
    tags: ["curry", "creamy", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Dal Makhani",
    cuisine: "north-indian", category: "dal", isVeg: true,
    imageUrl: `${W}/thumb/c/c3/Dal_makhani.JPG/800px-Dal_makhani.JPG`,
    aliases: ["maa ki dal", "black dal"],
    tags: ["dal", "creamy", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Dal Tadka",
    cuisine: "north-indian", category: "dal", isVeg: true,
    imageUrl: `${W}/thumb/8/89/Dal_Tadka.jpg/800px-Dal_Tadka.jpg`,
    aliases: ["yellow dal", "dal fry"],
    tags: ["dal"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Chana Masala",
    cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/8/8c/Chole_or_chana_masala.jpg/800px-Chole_or_chana_masala.jpg`,
    aliases: ["chole", "chickpea curry", "chole masala"],
    tags: ["curry", "chickpea"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Rajma",
    cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/0/07/Rajma_Chawal.jpg/800px-Rajma_Chawal.jpg`,
    aliases: ["rajma chawal", "kidney bean curry"],
    tags: ["curry", "comfort"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Aloo Gobi",
    cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/b/b1/Aloo_gobi.jpg/800px-Aloo_gobi.jpg`,
    aliases: ["potato cauliflower"],
    tags: ["dry-curry"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Malai Kofta",
    cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/6/6a/Malai_kofta.jpg/800px-Malai_kofta.jpg`,
    tags: ["curry", "creamy"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Baingan Bharta",
    cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/4/4a/Baingan_Bharta.JPG/800px-Baingan_Bharta.JPG`,
    aliases: ["smoked eggplant"],
    tags: ["smoky"],
    attribution: "Wikimedia Commons",
  },

  // ─── Breads ───────────────────────────────────────────────────
  {
    name: "Butter Naan",
    cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/7/73/Naan_Indian_bread.jpg/800px-Naan_Indian_bread.jpg`,
    aliases: ["naan", "plain naan"],
    tags: ["bread", "tandoor"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Garlic Naan",
    cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/40/Garlic_Naan_at_Mela_Restaurant_NYC_2.jpg/800px-Garlic_Naan_at_Mela_Restaurant_NYC_2.jpg`,
    tags: ["bread", "garlic"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Tandoori Roti",
    cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Tandoori_Roti.jpg/800px-Tandoori_Roti.jpg`,
    aliases: ["roti", "whole wheat roti"],
    tags: ["bread"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Aloo Paratha",
    cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4f/Aloo_paratha_November_2010.jpg/800px-Aloo_paratha_November_2010.jpg`,
    aliases: ["potato paratha"],
    tags: ["bread", "breakfast"],
    attribution: "Wikimedia Commons",
  },

  // ─── Rice ─────────────────────────────────────────────────────
  {
    name: "Jeera Rice",
    cuisine: "north-indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/f/f8/Jeera_Rice_at_Mela_Restaurant.jpg/800px-Jeera_Rice_at_Mela_Restaurant.jpg`,
    aliases: ["cumin rice"],
    tags: ["rice"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Veg Pulao",
    cuisine: "north-indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/8/82/Vegetable_pulao.jpg/800px-Vegetable_pulao.jpg`,
    aliases: ["vegetable pulao", "pulav", "veg pulav"],
    tags: ["rice"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Veg Biryani",
    cuisine: "north-indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/9/9c/Hyderabadi_vegetable_biryani.jpg/800px-Hyderabadi_vegetable_biryani.jpg`,
    aliases: ["vegetable biryani", "veggie biryani"],
    tags: ["rice", "biryani"],
    attribution: "Wikimedia Commons",
  },

  // ─── Non-veg ──────────────────────────────────────────────────
  {
    name: "Butter Chicken",
    cuisine: "north-indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/4/45/Butter_chicken_%282%29.jpg/800px-Butter_chicken_%282%29.jpg`,
    aliases: ["murgh makhani", "chicken makhani"],
    tags: ["curry", "creamy", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Chicken Tikka Masala",
    cuisine: "north-indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/4/4b/Chicken_Tikka_Masala_-_oven_baked.jpg/800px-Chicken_Tikka_Masala_-_oven_baked.jpg`,
    aliases: ["tikka masala", "ctm"],
    tags: ["curry", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Tandoori Chicken",
    cuisine: "north-indian", category: "starter", isVeg: false,
    imageUrl: `${W}/thumb/7/72/Tandoori_Chicken.JPG/800px-Tandoori_Chicken.JPG`,
    aliases: ["tandoori murgh"],
    tags: ["tandoor", "starter"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Chicken Tikka",
    cuisine: "north-indian", category: "starter", isVeg: false,
    imageUrl: `${W}/thumb/9/95/Chicken_Tikka.JPG/800px-Chicken_Tikka.JPG`,
    aliases: ["murgh tikka"],
    tags: ["tandoor", "starter"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Chicken Biryani",
    cuisine: "north-indian", category: "rice", isVeg: false,
    imageUrl: `${W}/thumb/6/68/Chicken_biryani.jpg/800px-Chicken_biryani.jpg`,
    aliases: ["murgh biryani", "hyderabadi biryani"],
    tags: ["rice", "biryani", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Mutton Biryani",
    cuisine: "north-indian", category: "rice", isVeg: false,
    imageUrl: `${W}/thumb/c/c8/Mutton_biryani.jpg/800px-Mutton_biryani.jpg`,
    aliases: ["lamb biryani", "gosht biryani"],
    tags: ["rice", "biryani"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Mutton Rogan Josh",
    cuisine: "north-indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/6/61/Rogan_Josh_with_naan_bread%2C_Kebabish_Grill%2C_Mt_Lebanon.jpg/800px-Rogan_Josh_with_naan_bread%2C_Kebabish_Grill%2C_Mt_Lebanon.jpg`,
    aliases: ["rogan josh"],
    tags: ["curry", "kashmiri"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Fish Curry",
    cuisine: "south-indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/b/b3/Fish_curry_kerala.jpg/800px-Fish_curry_kerala.jpg`,
    aliases: ["meen curry", "kerala fish curry"],
    tags: ["curry", "seafood"],
    attribution: "Wikimedia Commons",
  },

  // ─── South Indian ─────────────────────────────────────────────
  {
    name: "Masala Dosa",
    cuisine: "south-indian", category: "main", isVeg: true,
    imageUrl: `${W}/thumb/b/b9/Masala_Dosa_at_Sri_Krishna_Sweets%2C_Chennai.jpg/800px-Masala_Dosa_at_Sri_Krishna_Sweets%2C_Chennai.jpg`,
    aliases: ["dosa", "mysore masala dosa"],
    tags: ["breakfast", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Idli Sambar",
    cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/3/3c/Idli_with_Sambhar_and_chutneys.jpg/800px-Idli_with_Sambhar_and_chutneys.jpg`,
    aliases: ["idli", "idly"],
    tags: ["breakfast", "steamed"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Medu Vada",
    cuisine: "south-indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/4/47/Medu_Vada%2C_an_Indian_food.jpg/800px-Medu_Vada%2C_an_Indian_food.jpg`,
    aliases: ["vada", "ulundu vadai"],
    tags: ["fried", "snack"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Uttapam",
    cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/a/a0/Uttapam_with_chutney.jpg/800px-Uttapam_with_chutney.jpg`,
    aliases: ["uttappam", "onion uttapam"],
    tags: ["breakfast"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Sambar",
    cuisine: "south-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/7/73/Sambar_with_rice.jpg/800px-Sambar_with_rice.jpg`,
    tags: ["dal", "curry"],
    attribution: "Wikimedia Commons",
  },

  // ─── Street food / chaat ──────────────────────────────────────
  {
    name: "Samosa",
    cuisine: "north-indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c4/Samosachutney.jpg/800px-Samosachutney.jpg`,
    aliases: ["aloo samosa", "veg samosa"],
    tags: ["fried", "snack", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Pakora",
    cuisine: "north-indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/8/8f/Onion_pakora.jpg/800px-Onion_pakora.jpg`,
    aliases: ["pakoda", "bhajji", "onion pakora"],
    tags: ["fried", "snack"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Pav Bhaji",
    cuisine: "street", category: "main", isVeg: true,
    imageUrl: `${W}/thumb/1/1f/Pav_bhaji_at_Aaswad%2C_Dadar.jpg/800px-Pav_bhaji_at_Aaswad%2C_Dadar.jpg`,
    tags: ["street", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Vada Pav",
    cuisine: "street", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/d/d8/Vada_Pav_-_Bombay_Burger.jpg/800px-Vada_Pav_-_Bombay_Burger.jpg`,
    tags: ["street", "mumbai"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Pani Puri",
    cuisine: "street", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c4/Pani_Puri_or_Gol_Gappa.jpg/800px-Pani_Puri_or_Gol_Gappa.jpg`,
    aliases: ["gol gappa", "puchka"],
    tags: ["street", "chaat"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Bhel Puri",
    cuisine: "street", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/5/56/Bhelpuri.JPG/800px-Bhelpuri.JPG`,
    tags: ["street", "chaat"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Dhokla",
    cuisine: "gujarati", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c8/Dhokla.JPG/800px-Dhokla.JPG`,
    tags: ["steamed", "snack"],
    attribution: "Wikimedia Commons",
  },

  // ─── Desserts ─────────────────────────────────────────────────
  {
    name: "Gulab Jamun",
    cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/4/41/Gulab_jamun_%28Gibe3%29.JPG/800px-Gulab_jamun_%28Gibe3%29.JPG`,
    tags: ["dessert", "sweet", "popular"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Rasgulla",
    cuisine: "bengali", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/3/3c/Rasgulla_%28Ras_Gulla%29.jpg/800px-Rasgulla_%28Ras_Gulla%29.jpg`,
    aliases: ["roshogolla"],
    tags: ["dessert", "sweet"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Jalebi",
    cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/0/05/Jalebi.JPG/800px-Jalebi.JPG`,
    tags: ["dessert", "sweet", "fried"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Kulfi",
    cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/3/3f/Pista_kulfi.jpg/800px-Pista_kulfi.jpg`,
    aliases: ["pista kulfi", "malai kulfi"],
    tags: ["dessert", "frozen"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Gajar Halwa",
    cuisine: "north-indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/9/92/Gajar_halwa_served_in_a_bowl.jpg/800px-Gajar_halwa_served_in_a_bowl.jpg`,
    aliases: ["carrot halwa", "gajrela"],
    tags: ["dessert", "sweet"],
    attribution: "Wikimedia Commons",
  },

  // ─── Beverages ────────────────────────────────────────────────
  {
    name: "Masala Chai",
    cuisine: "indian", category: "beverage", isVeg: true,
    imageUrl: `${W}/thumb/4/4a/Masala_Chai.jpg/800px-Masala_Chai.jpg`,
    aliases: ["chai", "spiced tea", "indian tea"],
    tags: ["beverage", "hot"],
    attribution: "Wikimedia Commons",
  },
  {
    name: "Mango Lassi",
    cuisine: "indian", category: "beverage", isVeg: true,
    imageUrl: `${W}/thumb/0/05/Mango_lassi.jpg/800px-Mango_lassi.jpg`,
    aliases: ["lassi", "sweet lassi"],
    tags: ["beverage", "cold"],
    attribution: "Wikimedia Commons",
  },

  // ─── Expanded catalog — North Indian curries ─────────────────
  { name: "Kadhi Pakora", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/2/2c/Kadhi.jpg/800px-Kadhi.jpg`,
    aliases: ["kadhi", "punjabi kadhi"], tags: ["curry", "yogurt"], attribution: "Wikimedia Commons" },
  { name: "Bhindi Masala", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/d/d5/Bhindi_masala.jpg/800px-Bhindi_masala.jpg`,
    aliases: ["okra masala", "bhindi do pyaza"], tags: ["curry", "okra"], attribution: "Wikimedia Commons" },
  { name: "Baingan Bharta", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/3/33/Baingan_bharta.jpg/800px-Baingan_bharta.jpg`,
    aliases: ["smoked eggplant", "begun bhorta"], tags: ["curry", "eggplant"], attribution: "Wikimedia Commons" },
  { name: "Aloo Baingan", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/3/33/Baingan_bharta.jpg/800px-Baingan_bharta.jpg`,
    aliases: ["potato eggplant"], tags: ["curry"], attribution: "Wikimedia Commons" },
  { name: "Aloo Methi", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/a/a4/Aloo_methi.jpg/800px-Aloo_methi.jpg`,
    aliases: ["fenugreek potato"], tags: ["curry", "fenugreek"], attribution: "Wikimedia Commons" },
  { name: "Aloo Jeera", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/3/3b/Jeera_Aloo.jpg/800px-Jeera_Aloo.jpg`,
    aliases: ["jeera aloo", "cumin potato"], tags: ["dry", "potato"], attribution: "Wikimedia Commons" },
  { name: "Aloo Matar", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/2/23/Aloo_Matar.jpg/800px-Aloo_Matar.jpg`,
    aliases: ["pea potato curry"], tags: ["curry", "peas"], attribution: "Wikimedia Commons" },
  { name: "Matar Paneer", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/c/c0/Matar_paneer.jpg/800px-Matar_paneer.jpg`,
    aliases: ["pea paneer", "paneer matar"], tags: ["curry", "paneer", "peas"], attribution: "Wikimedia Commons" },
  { name: "Malai Kofta", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/0/00/Malai_Kofta.jpg/800px-Malai_Kofta.jpg`,
    aliases: ["kofta curry"], tags: ["curry", "creamy"], attribution: "Wikimedia Commons" },
  { name: "Navratan Korma", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Navratan_korma.jpg/800px-Navratan_korma.jpg`,
    aliases: ["nine jewel korma"], tags: ["curry", "creamy"], attribution: "Wikimedia Commons" },
  { name: "Veg Kolhapuri", cuisine: "maharashtrian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/d/d5/Veg_kolhapuri.jpg/800px-Veg_kolhapuri.jpg`,
    aliases: ["mixed veg kolhapuri"], tags: ["curry", "spicy"], attribution: "Wikimedia Commons" },
  { name: "Mixed Vegetable Curry", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/d/d5/Veg_kolhapuri.jpg/800px-Veg_kolhapuri.jpg`,
    aliases: ["mix veg", "subzi"], tags: ["curry"], attribution: "Wikimedia Commons" },
  { name: "Methi Malai Mutter", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/a/a4/Aloo_methi.jpg/800px-Aloo_methi.jpg`,
    aliases: ["methi mutter malai"], tags: ["curry", "creamy"], attribution: "Wikimedia Commons" },
  { name: "Dum Aloo", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/e/eb/Kashmiri_Dum_aloo.jpg/800px-Kashmiri_Dum_aloo.jpg`,
    aliases: ["kashmiri dum aloo"], tags: ["curry", "potato"], attribution: "Wikimedia Commons" },
  { name: "Rajma Chawal", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/2/27/Rajma_Chawal.jpg/800px-Rajma_Chawal.jpg`,
    aliases: ["rajma rice", "kidney bean curry"], tags: ["curry", "rice"], attribution: "Wikimedia Commons" },
  { name: "Pindi Chana", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Chana_masala_-_Indian_food_recipe.jpg/800px-Chana_masala_-_Indian_food_recipe.jpg`,
    aliases: ["pindi chole", "amritsari chole"], tags: ["curry", "chickpea"], attribution: "Wikimedia Commons" },
  { name: "Chole Bhature", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/c/c7/Chole_Bhature.jpg/800px-Chole_Bhature.jpg`,
    aliases: ["bhature chole"], tags: ["curry", "bread", "popular"], attribution: "Wikimedia Commons" },
  { name: "Kadai Paneer", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/f/f0/Paneer_makhani.JPG/800px-Paneer_makhani.JPG`,
    aliases: ["karahi paneer"], tags: ["curry", "paneer"], attribution: "Wikimedia Commons" },
  { name: "Shahi Paneer", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/f/f0/Paneer_makhani.JPG/800px-Paneer_makhani.JPG`,
    aliases: ["royal paneer"], tags: ["curry", "creamy", "rich"], attribution: "Wikimedia Commons" },
  { name: "Paneer Bhurji", cuisine: "north-indian", category: "starter", isVeg: true,
    imageUrl: `${W}/thumb/d/d2/Paneer_bhurji.jpg/800px-Paneer_bhurji.jpg`,
    aliases: ["scrambled paneer"], tags: ["paneer", "dry"], attribution: "Wikimedia Commons" },

  // ─── Non-veg additions ────────────────────────────────────────
  { name: "Mutton Rogan Josh", cuisine: "kashmiri", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/a/a3/Rogan_Josh.jpg/800px-Rogan_Josh.jpg`,
    aliases: ["rogan josh", "kashmiri mutton"], tags: ["curry", "mutton"], attribution: "Wikimedia Commons" },
  { name: "Chicken Korma", cuisine: "mughlai", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/8/8b/Chicken_Korma.jpg/800px-Chicken_Korma.jpg`,
    aliases: ["murgh korma"], tags: ["curry", "chicken", "creamy"], attribution: "Wikimedia Commons" },
  { name: "Chicken Chettinad", cuisine: "south-indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/8/8b/Chicken_Korma.jpg/800px-Chicken_Korma.jpg`,
    aliases: ["chettinad chicken"], tags: ["curry", "spicy"], attribution: "Wikimedia Commons" },
  { name: "Chicken Vindaloo", cuisine: "goan", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/b/b9/Vindaloo.jpg/800px-Vindaloo.jpg`,
    aliases: ["vindaloo"], tags: ["curry", "spicy", "goan"], attribution: "Wikimedia Commons" },
  { name: "Fish Curry", cuisine: "indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/3/3a/Fish_curry.jpg/800px-Fish_curry.jpg`,
    aliases: ["machli curry", "macher jhol"], tags: ["curry", "fish"], attribution: "Wikimedia Commons" },
  { name: "Goan Fish Curry", cuisine: "goan", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/3/3a/Fish_curry.jpg/800px-Fish_curry.jpg`,
    aliases: ["goan curry"], tags: ["curry", "fish", "coconut"], attribution: "Wikimedia Commons" },
  { name: "Prawn Masala", cuisine: "indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/3/3a/Fish_curry.jpg/800px-Fish_curry.jpg`,
    aliases: ["prawn curry", "shrimp masala"], tags: ["curry", "seafood"], attribution: "Wikimedia Commons" },
  { name: "Chicken 65", cuisine: "south-indian", category: "starter", isVeg: false,
    imageUrl: `${W}/thumb/4/49/Chicken_65_-_Bangalore_style.jpg/800px-Chicken_65_-_Bangalore_style.jpg`,
    aliases: ["chicken sixty five"], tags: ["starter", "fried", "spicy"], attribution: "Wikimedia Commons" },
  { name: "Tandoori Chicken", cuisine: "north-indian", category: "starter", isVeg: false,
    imageUrl: `${W}/thumb/d/dc/Tandoori_chicken_with_lemon.jpg/800px-Tandoori_chicken_with_lemon.jpg`,
    aliases: ["tandoor chicken"], tags: ["tandoor", "popular"], attribution: "Wikimedia Commons" },
  { name: "Chicken Tikka", cuisine: "north-indian", category: "starter", isVeg: false,
    imageUrl: `${W}/thumb/d/dc/Tandoori_chicken_with_lemon.jpg/800px-Tandoori_chicken_with_lemon.jpg`,
    aliases: ["murgh tikka"], tags: ["tandoor", "starter"], attribution: "Wikimedia Commons" },
  { name: "Chicken Tikka Masala", cuisine: "north-indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/9/91/Chicken_tikka_masala.jpg/800px-Chicken_tikka_masala.jpg`,
    aliases: ["ctm", "tikka masala"], tags: ["curry", "creamy", "popular"], attribution: "Wikimedia Commons" },
  { name: "Butter Chicken", cuisine: "north-indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/9/91/Chicken_tikka_masala.jpg/800px-Chicken_tikka_masala.jpg`,
    aliases: ["murgh makhani"], tags: ["curry", "creamy", "popular"], attribution: "Wikimedia Commons" },
  { name: "Egg Curry", cuisine: "indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/3/3a/Fish_curry.jpg/800px-Fish_curry.jpg`,
    aliases: ["anda curry"], tags: ["curry", "egg"], attribution: "Wikimedia Commons" },
  { name: "Keema Matar", cuisine: "mughlai", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/a/a3/Rogan_Josh.jpg/800px-Rogan_Josh.jpg`,
    aliases: ["mutton keema", "keema mutter"], tags: ["curry", "mince"], attribution: "Wikimedia Commons" },
  { name: "Mutton Biryani", cuisine: "hyderabadi", category: "rice", isVeg: false,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["lamb biryani"], tags: ["rice", "biryani", "popular"], attribution: "Wikimedia Commons" },
  { name: "Chicken Biryani", cuisine: "hyderabadi", category: "rice", isVeg: false,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["murgh biryani"], tags: ["rice", "biryani", "popular"], attribution: "Wikimedia Commons" },

  // ─── Rice & biryanis ──────────────────────────────────────────
  { name: "Veg Biryani", cuisine: "indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["vegetable biryani"], tags: ["rice", "biryani"], attribution: "Wikimedia Commons" },
  { name: "Pulao", cuisine: "indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["pilaf", "pilau"], tags: ["rice"], attribution: "Wikimedia Commons" },
  { name: "Jeera Rice", cuisine: "indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["cumin rice"], tags: ["rice"], attribution: "Wikimedia Commons" },
  { name: "Steamed Rice", cuisine: "indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["plain rice", "boiled rice"], tags: ["rice"], attribution: "Wikimedia Commons" },
  { name: "Curd Rice", cuisine: "south-indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["thayir sadam", "dahi chawal"], tags: ["rice", "yogurt"], attribution: "Wikimedia Commons" },
  { name: "Lemon Rice", cuisine: "south-indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["chitranna"], tags: ["rice"], attribution: "Wikimedia Commons" },
  { name: "Tamarind Rice", cuisine: "south-indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["puliyodarai", "pulihora"], tags: ["rice"], attribution: "Wikimedia Commons" },

  // ─── Breads ───────────────────────────────────────────────────
  { name: "Tandoori Roti", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["roti"], tags: ["bread", "tandoor"], attribution: "Wikimedia Commons" },
  { name: "Butter Naan", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["naan"], tags: ["bread", "tandoor", "popular"], attribution: "Wikimedia Commons" },
  { name: "Garlic Naan", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["lehsuni naan"], tags: ["bread", "tandoor", "popular"], attribution: "Wikimedia Commons" },
  { name: "Lachha Paratha", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["layered paratha"], tags: ["bread"], attribution: "Wikimedia Commons" },
  { name: "Aloo Paratha", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["stuffed potato paratha"], tags: ["bread", "breakfast", "popular"], attribution: "Wikimedia Commons" },
  { name: "Paneer Paratha", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["stuffed paneer paratha"], tags: ["bread", "breakfast"], attribution: "Wikimedia Commons" },
  { name: "Gobi Paratha", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["cauliflower paratha"], tags: ["bread"], attribution: "Wikimedia Commons" },
  { name: "Mooli Paratha", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["radish paratha"], tags: ["bread"], attribution: "Wikimedia Commons" },
  { name: "Bhatura", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/c/c7/Chole_Bhature.jpg/800px-Chole_Bhature.jpg`,
    aliases: ["bhature"], tags: ["bread", "fried"], attribution: "Wikimedia Commons" },
  { name: "Puri", cuisine: "indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/c/c7/Chole_Bhature.jpg/800px-Chole_Bhature.jpg`,
    aliases: ["poori"], tags: ["bread", "fried"], attribution: "Wikimedia Commons" },
  { name: "Kulcha", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["amritsari kulcha"], tags: ["bread"], attribution: "Wikimedia Commons" },

  // ─── South Indian ─────────────────────────────────────────────
  { name: "Masala Dosa", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/6/6c/Masala_Dosa_at_Sri_Sagar_in_Bangalore.jpg/800px-Masala_Dosa_at_Sri_Sagar_in_Bangalore.jpg`,
    aliases: ["dosa masala"], tags: ["breakfast", "popular"], attribution: "Wikimedia Commons" },
  { name: "Plain Dosa", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/6/6c/Masala_Dosa_at_Sri_Sagar_in_Bangalore.jpg/800px-Masala_Dosa_at_Sri_Sagar_in_Bangalore.jpg`,
    aliases: ["dosa", "sada dosa"], tags: ["breakfast"], attribution: "Wikimedia Commons" },
  { name: "Rava Dosa", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/6/6c/Masala_Dosa_at_Sri_Sagar_in_Bangalore.jpg/800px-Masala_Dosa_at_Sri_Sagar_in_Bangalore.jpg`,
    aliases: ["semolina dosa"], tags: ["breakfast"], attribution: "Wikimedia Commons" },
  { name: "Idli", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["idly", "idli sambar"], tags: ["breakfast", "popular"], attribution: "Wikimedia Commons" },
  { name: "Medu Vada", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["vada", "uddina vada"], tags: ["breakfast", "fried"], attribution: "Wikimedia Commons" },
  { name: "Uttapam", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/6/6c/Masala_Dosa_at_Sri_Sagar_in_Bangalore.jpg/800px-Masala_Dosa_at_Sri_Sagar_in_Bangalore.jpg`,
    aliases: ["uttappa", "onion uttapam"], tags: ["breakfast"], attribution: "Wikimedia Commons" },
  { name: "Upma", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["uppittu"], tags: ["breakfast"], attribution: "Wikimedia Commons" },
  { name: "Pongal", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["ven pongal"], tags: ["breakfast", "rice"], attribution: "Wikimedia Commons" },
  { name: "Sambar", cuisine: "south-indian", category: "dal", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["sambhar"], tags: ["dal", "lentil"], attribution: "Wikimedia Commons" },
  { name: "Rasam", cuisine: "south-indian", category: "soup", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["tomato rasam"], tags: ["soup", "tangy"], attribution: "Wikimedia Commons" },
  { name: "Coconut Chutney", cuisine: "south-indian", category: "condiment", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["nariyal chutney"], tags: ["condiment"], attribution: "Wikimedia Commons" },

  // ─── Street food & chaat ──────────────────────────────────────
  { name: "Pav Bhaji", cuisine: "maharashtrian", category: "street", isVeg: true,
    imageUrl: `${W}/thumb/6/6c/Pav_Bhaji_-_Mumbai_Street_Food.jpg/800px-Pav_Bhaji_-_Mumbai_Street_Food.jpg`,
    aliases: ["bhaji pav"], tags: ["street", "popular"], attribution: "Wikimedia Commons" },
  { name: "Vada Pav", cuisine: "maharashtrian", category: "street", isVeg: true,
    imageUrl: `${W}/thumb/6/6c/Pav_Bhaji_-_Mumbai_Street_Food.jpg/800px-Pav_Bhaji_-_Mumbai_Street_Food.jpg`,
    aliases: ["wada pav"], tags: ["street", "mumbai"], attribution: "Wikimedia Commons" },
  { name: "Misal Pav", cuisine: "maharashtrian", category: "street", isVeg: true,
    imageUrl: `${W}/thumb/6/6c/Pav_Bhaji_-_Mumbai_Street_Food.jpg/800px-Pav_Bhaji_-_Mumbai_Street_Food.jpg`,
    aliases: ["misal"], tags: ["street", "spicy"], attribution: "Wikimedia Commons" },
  { name: "Pani Puri", cuisine: "indian", category: "street", isVeg: true,
    imageUrl: `${W}/thumb/b/b8/Pani_Puri.jpg/800px-Pani_Puri.jpg`,
    aliases: ["golgappa", "puchka", "phuchka"], tags: ["street", "popular"], attribution: "Wikimedia Commons" },
  { name: "Bhel Puri", cuisine: "indian", category: "street", isVeg: true,
    imageUrl: `${W}/thumb/9/94/Bhelpuri.jpg/800px-Bhelpuri.jpg`,
    aliases: ["bhel"], tags: ["street", "chaat"], attribution: "Wikimedia Commons" },
  { name: "Sev Puri", cuisine: "indian", category: "street", isVeg: true,
    imageUrl: `${W}/thumb/9/94/Bhelpuri.jpg/800px-Bhelpuri.jpg`,
    aliases: ["sevpuri"], tags: ["street", "chaat"], attribution: "Wikimedia Commons" },
  { name: "Dahi Puri", cuisine: "indian", category: "street", isVeg: true,
    imageUrl: `${W}/thumb/9/94/Bhelpuri.jpg/800px-Bhelpuri.jpg`,
    aliases: ["dahipuri"], tags: ["street", "chaat", "yogurt"], attribution: "Wikimedia Commons" },
  { name: "Aloo Tikki", cuisine: "north-indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/9/94/Bhelpuri.jpg/800px-Bhelpuri.jpg`,
    aliases: ["tikki", "potato patty"], tags: ["snack", "chaat"], attribution: "Wikimedia Commons" },
  { name: "Dahi Vada", cuisine: "indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/9/94/Bhelpuri.jpg/800px-Bhelpuri.jpg`,
    aliases: ["dahi bhalla"], tags: ["snack", "yogurt"], attribution: "Wikimedia Commons" },
  { name: "Papdi Chaat", cuisine: "north-indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/9/94/Bhelpuri.jpg/800px-Bhelpuri.jpg`,
    aliases: ["papri chaat"], tags: ["snack", "chaat"], attribution: "Wikimedia Commons" },
  { name: "Kachori", cuisine: "north-indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c7/Chole_Bhature.jpg/800px-Chole_Bhature.jpg`,
    aliases: ["khasta kachori", "raj kachori"], tags: ["snack", "fried"], attribution: "Wikimedia Commons" },
  { name: "Samosa", cuisine: "indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/3/38/Samosa-and-Chutney.jpg/800px-Samosa-and-Chutney.jpg`,
    aliases: ["singhara"], tags: ["snack", "fried", "popular"], attribution: "Wikimedia Commons" },
  { name: "Onion Pakora", cuisine: "indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/3/38/Samosa-and-Chutney.jpg/800px-Samosa-and-Chutney.jpg`,
    aliases: ["pakora", "kanda bhajiya"], tags: ["snack", "fried"], attribution: "Wikimedia Commons" },
  { name: "Vegetable Pakora", cuisine: "indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/3/38/Samosa-and-Chutney.jpg/800px-Samosa-and-Chutney.jpg`,
    aliases: ["mix pakora"], tags: ["snack", "fried"], attribution: "Wikimedia Commons" },

  // ─── Indo-Chinese ─────────────────────────────────────────────
  { name: "Gobi Manchurian", cuisine: "indo-chinese", category: "starter", isVeg: true,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["cauliflower manchurian"], tags: ["indo-chinese", "starter"], attribution: "Wikimedia Commons" },
  { name: "Chilli Paneer", cuisine: "indo-chinese", category: "starter", isVeg: true,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["chilly paneer"], tags: ["indo-chinese", "starter"], attribution: "Wikimedia Commons" },
  { name: "Veg Manchurian", cuisine: "indo-chinese", category: "starter", isVeg: true,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["vegetable manchurian"], tags: ["indo-chinese"], attribution: "Wikimedia Commons" },
  { name: "Chilli Chicken", cuisine: "indo-chinese", category: "starter", isVeg: false,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["chilly chicken"], tags: ["indo-chinese", "chicken"], attribution: "Wikimedia Commons" },
  { name: "Hakka Noodles", cuisine: "indo-chinese", category: "noodles", isVeg: true,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["veg hakka", "chow"], tags: ["noodles", "indo-chinese"], attribution: "Wikimedia Commons" },
  { name: "Schezwan Noodles", cuisine: "indo-chinese", category: "noodles", isVeg: true,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["szechuan noodles"], tags: ["noodles", "spicy"], attribution: "Wikimedia Commons" },
  { name: "Fried Rice", cuisine: "indo-chinese", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/0/04/Hyderabadi_Mutton_Biryani.jpg/800px-Hyderabadi_Mutton_Biryani.jpg`,
    aliases: ["veg fried rice", "chinese rice"], tags: ["rice", "indo-chinese"], attribution: "Wikimedia Commons" },
  { name: "Spring Roll", cuisine: "indo-chinese", category: "starter", isVeg: true,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["veg spring roll"], tags: ["starter", "fried"], attribution: "Wikimedia Commons" },
  { name: "Manchow Soup", cuisine: "indo-chinese", category: "soup", isVeg: true,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["manchao"], tags: ["soup"], attribution: "Wikimedia Commons" },
  { name: "Hot and Sour Soup", cuisine: "indo-chinese", category: "soup", isVeg: true,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["hot sour soup"], tags: ["soup"], attribution: "Wikimedia Commons" },
  { name: "Sweet Corn Soup", cuisine: "indo-chinese", category: "soup", isVeg: true,
    imageUrl: `${W}/thumb/9/95/Gobi_manchurian.jpg/800px-Gobi_manchurian.jpg`,
    aliases: ["corn soup"], tags: ["soup"], attribution: "Wikimedia Commons" },

  // ─── Desserts ─────────────────────────────────────────────────
  { name: "Gulab Jamun", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/8/82/Gulab_Jamun_Recipe.jpg/800px-Gulab_Jamun_Recipe.jpg`,
    aliases: ["gulabjamun"], tags: ["dessert", "popular"], attribution: "Wikimedia Commons" },
  { name: "Rasgulla", cuisine: "bengali", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["roshogolla"], tags: ["dessert", "bengali"], attribution: "Wikimedia Commons" },
  { name: "Rasmalai", cuisine: "bengali", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["ras malai"], tags: ["dessert", "creamy"], attribution: "Wikimedia Commons" },
  { name: "Jalebi", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/c/c8/Jalebi.jpg/800px-Jalebi.jpg`,
    aliases: ["jilebi"], tags: ["dessert", "fried"], attribution: "Wikimedia Commons" },
  { name: "Kheer", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["rice kheer", "payasam"], tags: ["dessert"], attribution: "Wikimedia Commons" },
  { name: "Gajar Halwa", cuisine: "north-indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["gajar ka halwa", "carrot halwa"], tags: ["dessert", "winter"], attribution: "Wikimedia Commons" },
  { name: "Moong Dal Halwa", cuisine: "north-indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["moong halwa"], tags: ["dessert"], attribution: "Wikimedia Commons" },
  { name: "Kulfi", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["malai kulfi", "indian ice cream"], tags: ["dessert", "cold"], attribution: "Wikimedia Commons" },
  { name: "Falooda", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["faluda"], tags: ["dessert", "cold"], attribution: "Wikimedia Commons" },
  { name: "Mysore Pak", cuisine: "south-indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["mysorepak"], tags: ["dessert"], attribution: "Wikimedia Commons" },
  { name: "Sandesh", cuisine: "bengali", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["shondesh"], tags: ["dessert", "bengali"], attribution: "Wikimedia Commons" },
  { name: "Modak", cuisine: "maharashtrian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/5/5e/Rasgulla_Closeup.jpg/800px-Rasgulla_Closeup.jpg`,
    aliases: ["ukadiche modak"], tags: ["dessert"], attribution: "Wikimedia Commons" },

  // ─── Beverages (extra) ────────────────────────────────────────
  { name: "Sweet Lassi", cuisine: "north-indian", category: "beverage", isVeg: true,
    imageUrl: `${W}/thumb/0/05/Mango_lassi.jpg/800px-Mango_lassi.jpg`,
    aliases: ["meethi lassi"], tags: ["beverage", "cold"], attribution: "Wikimedia Commons" },
  { name: "Salted Lassi", cuisine: "north-indian", category: "beverage", isVeg: true,
    imageUrl: `${W}/thumb/0/05/Mango_lassi.jpg/800px-Mango_lassi.jpg`,
    aliases: ["namkeen lassi"], tags: ["beverage", "cold"], attribution: "Wikimedia Commons" },
  { name: "Buttermilk", cuisine: "indian", category: "beverage", isVeg: true,
    imageUrl: `${W}/thumb/0/05/Mango_lassi.jpg/800px-Mango_lassi.jpg`,
    aliases: ["chaas", "chhaas"], tags: ["beverage", "cold"], attribution: "Wikimedia Commons" },
  { name: "Filter Coffee", cuisine: "south-indian", category: "beverage", isVeg: true,
    imageUrl: `${W}/thumb/4/4a/Masala_Chai.jpg/800px-Masala_Chai.jpg`,
    aliases: ["south indian coffee", "kaapi"], tags: ["beverage", "hot"], attribution: "Wikimedia Commons" },
  { name: "Nimbu Pani", cuisine: "indian", category: "beverage", isVeg: true,
    imageUrl: `${W}/thumb/0/05/Mango_lassi.jpg/800px-Mango_lassi.jpg`,
    aliases: ["lemonade", "shikanji"], tags: ["beverage", "cold"], attribution: "Wikimedia Commons" },

  // ─── Bengali / Eastern ────────────────────────────────────────
  { name: "Macher Jhol", cuisine: "bengali", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/3/3a/Fish_curry.jpg/800px-Fish_curry.jpg`,
    aliases: ["bengali fish curry"], tags: ["curry", "fish"], attribution: "Wikimedia Commons" },
  { name: "Aloo Posto", cuisine: "bengali", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/a/a4/Aloo_methi.jpg/800px-Aloo_methi.jpg`,
    aliases: ["potato poppy seed"], tags: ["curry"], attribution: "Wikimedia Commons" },
  { name: "Shorshe Ilish", cuisine: "bengali", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/3/3a/Fish_curry.jpg/800px-Fish_curry.jpg`,
    aliases: ["hilsa mustard"], tags: ["curry", "fish"], attribution: "Wikimedia Commons" },

  // ─── Gujarati / Rajasthani ────────────────────────────────────
  { name: "Dhokla", cuisine: "gujarati", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["khaman dhokla"], tags: ["snack", "steamed"], attribution: "Wikimedia Commons" },
  { name: "Khandvi", cuisine: "gujarati", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["surali vadi"], tags: ["snack"], attribution: "Wikimedia Commons" },
  { name: "Thepla", cuisine: "gujarati", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["methi thepla"], tags: ["bread"], attribution: "Wikimedia Commons" },
  { name: "Dal Baati Churma", cuisine: "rajasthani", category: "meal", isVeg: true,
    imageUrl: `${W}/thumb/c/c3/Dal_makhani.JPG/800px-Dal_makhani.JPG`,
    aliases: ["dal baati"], tags: ["meal", "thali"], attribution: "Wikimedia Commons" },
  { name: "Gatte Ki Sabzi", cuisine: "rajasthani", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/a/a4/Aloo_methi.jpg/800px-Aloo_methi.jpg`,
    aliases: ["gatta curry"], tags: ["curry"], attribution: "Wikimedia Commons" },
  { name: "Laal Maas", cuisine: "rajasthani", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/a/a3/Rogan_Josh.jpg/800px-Rogan_Josh.jpg`,
    aliases: ["red mutton curry"], tags: ["curry", "spicy", "mutton"], attribution: "Wikimedia Commons" },

  // ─── Indian — expanded 2026-05 (Admin Food Image Library) ───────
  { name: "Kadai Paneer", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/f/f0/Paneer_makhani.JPG/800px-Paneer_makhani.JPG`,
    aliases: ["karahi paneer"], tags: ["curry", "spicy"], spiceLevel: 2, dietaryType: "veg", mealType: "main",
    attribution: "Wikimedia Commons" },
  { name: "Shahi Paneer", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/f/f0/Paneer_makhani.JPG/800px-Paneer_makhani.JPG`,
    aliases: ["royal paneer"], tags: ["curry", "creamy"], spiceLevel: 1, dietaryType: "veg", mealType: "main",
    attribution: "Wikimedia Commons" },
  { name: "Methi Malai Paneer", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/f/f0/Paneer_makhani.JPG/800px-Paneer_makhani.JPG`,
    aliases: ["methi paneer"], tags: ["curry", "creamy", "fenugreek"], dietaryType: "veg",
    attribution: "Wikimedia Commons" },
  { name: "Chana Masala", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/c/c3/Dal_makhani.JPG/800px-Dal_makhani.JPG`,
    aliases: ["chole", "chickpea curry"], tags: ["curry", "popular"], spiceLevel: 2, dietaryType: "vegan", mealType: "main",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Rajma Chawal", cuisine: "north-indian", category: "meal", isVeg: true,
    imageUrl: `${W}/thumb/c/c3/Dal_makhani.JPG/800px-Dal_makhani.JPG`,
    aliases: ["rajma rice"], tags: ["meal", "comfort"], dietaryType: "veg", mealType: "main",
    attribution: "Wikimedia Commons" },
  { name: "Aloo Gobi", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/a/a4/Aloo_methi.jpg/800px-Aloo_methi.jpg`,
    aliases: ["potato cauliflower"], tags: ["curry", "dry"], dietaryType: "vegan", mealType: "side",
    attribution: "Wikimedia Commons" },
  { name: "Baingan Bharta", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/a/a4/Aloo_methi.jpg/800px-Aloo_methi.jpg`,
    aliases: ["smoked eggplant"], tags: ["curry", "smoky"], dietaryType: "vegan", mealType: "side",
    attribution: "Wikimedia Commons" },
  { name: "Bhindi Masala", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/a/a4/Aloo_methi.jpg/800px-Aloo_methi.jpg`,
    aliases: ["okra masala"], tags: ["curry", "dry"], dietaryType: "vegan", mealType: "side",
    attribution: "Wikimedia Commons" },
  { name: "Mushroom Masala", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/a/a4/Aloo_methi.jpg/800px-Aloo_methi.jpg`,
    aliases: ["mushroom curry"], tags: ["curry"], dietaryType: "vegan", attribution: "Wikimedia Commons" },
  { name: "Mix Veg Curry", cuisine: "north-indian", category: "curry", isVeg: true,
    imageUrl: `${W}/thumb/a/a4/Aloo_methi.jpg/800px-Aloo_methi.jpg`,
    aliases: ["mixed vegetable"], tags: ["curry"], dietaryType: "veg", mealType: "side",
    attribution: "Wikimedia Commons" },
  { name: "Tandoori Chicken", cuisine: "north-indian", category: "starter", isVeg: false,
    imageUrl: `${W}/thumb/3/30/Paneer_Tikka_at_Velleeswarar_Sannathi_Restaurant%2C_Chennai.jpg/800px-Paneer_Tikka_at_Velleeswarar_Sannathi_Restaurant%2C_Chennai.jpg`,
    aliases: ["tandoori murgh"], tags: ["tandoori", "popular"], spiceLevel: 2, dietaryType: "non-veg", mealType: "starter",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Chicken Tikka Masala", cuisine: "north-indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/a/a3/Rogan_Josh.jpg/800px-Rogan_Josh.jpg`,
    aliases: ["ctm", "tikka masala"], tags: ["curry", "popular"], spiceLevel: 2, dietaryType: "non-veg", mealType: "main",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Chicken Korma", cuisine: "north-indian", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/a/a3/Rogan_Josh.jpg/800px-Rogan_Josh.jpg`,
    aliases: ["murgh korma"], tags: ["curry", "creamy"], spiceLevel: 1, dietaryType: "non-veg",
    attribution: "Wikimedia Commons" },
  { name: "Mutton Rogan Josh", cuisine: "kashmiri", category: "curry", isVeg: false,
    imageUrl: `${W}/thumb/a/a3/Rogan_Josh.jpg/800px-Rogan_Josh.jpg`,
    aliases: ["rogan josh"], tags: ["curry", "mutton", "spicy"], spiceLevel: 3, dietaryType: "non-veg", mealType: "main",
    attribution: "Wikimedia Commons" },
  { name: "Chicken Biryani", cuisine: "hyderabadi", category: "rice", isVeg: false,
    imageUrl: `${W}/thumb/9/97/Chicken_Biryani.jpg/800px-Chicken_Biryani.jpg`,
    aliases: ["murgh biryani"], tags: ["rice", "biryani", "popular"], spiceLevel: 2, dietaryType: "non-veg", mealType: "rice",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Veg Biryani", cuisine: "hyderabadi", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/9/97/Chicken_Biryani.jpg/800px-Chicken_Biryani.jpg`,
    aliases: ["vegetable biryani"], tags: ["rice", "biryani"], spiceLevel: 2, dietaryType: "veg", mealType: "rice",
    attribution: "Wikimedia Commons" },
  { name: "Mutton Biryani", cuisine: "hyderabadi", category: "rice", isVeg: false,
    imageUrl: `${W}/thumb/9/97/Chicken_Biryani.jpg/800px-Chicken_Biryani.jpg`,
    aliases: ["lamb biryani"], tags: ["rice", "biryani"], spiceLevel: 2, dietaryType: "non-veg", mealType: "rice",
    attribution: "Wikimedia Commons" },
  { name: "Egg Biryani", cuisine: "indian", category: "rice", isVeg: false,
    imageUrl: `${W}/thumb/9/97/Chicken_Biryani.jpg/800px-Chicken_Biryani.jpg`,
    aliases: ["anda biryani"], tags: ["rice", "egg"], spiceLevel: 2, dietaryType: "egg", mealType: "rice",
    attribution: "Wikimedia Commons" },
  { name: "Jeera Rice", cuisine: "indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/9/97/Chicken_Biryani.jpg/800px-Chicken_Biryani.jpg`,
    aliases: ["cumin rice"], tags: ["rice", "side"], dietaryType: "vegan", mealType: "side",
    attribution: "Wikimedia Commons" },
  { name: "Pulao", cuisine: "indian", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/9/97/Chicken_Biryani.jpg/800px-Chicken_Biryani.jpg`,
    aliases: ["pilaf", "vegetable pulao"], tags: ["rice"], dietaryType: "veg", mealType: "rice",
    attribution: "Wikimedia Commons" },
  { name: "Garlic Naan", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["lehsuni naan"], tags: ["bread", "tandoori"], dietaryType: "veg", mealType: "bread",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Butter Naan", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["makhan naan"], tags: ["bread"], dietaryType: "veg", mealType: "bread",
    attribution: "Wikimedia Commons" },
  { name: "Tandoori Roti", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["roti"], tags: ["bread"], dietaryType: "vegan", mealType: "bread",
    attribution: "Wikimedia Commons" },
  { name: "Lachha Paratha", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["layered paratha"], tags: ["bread"], dietaryType: "veg", mealType: "bread",
    attribution: "Wikimedia Commons" },
  { name: "Paneer Kulcha", cuisine: "north-indian", category: "bread", isVeg: true,
    imageUrl: `${W}/thumb/4/4d/Tandoori_roti.jpg/800px-Tandoori_roti.jpg`,
    aliases: ["amritsari kulcha"], tags: ["bread", "stuffed"], dietaryType: "veg", mealType: "bread",
    attribution: "Wikimedia Commons" },
  { name: "Masala Chai", cuisine: "indian", category: "drink", isVeg: true,
    imageUrl: `${W}/thumb/2/2a/Indian_Masala_Chai.jpg/800px-Indian_Masala_Chai.jpg`,
    aliases: ["chai", "spiced tea"], tags: ["drink", "popular"], dietaryType: "veg", mealType: "drink",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Mango Lassi", cuisine: "indian", category: "drink", isVeg: true,
    imageUrl: `${W}/thumb/2/2a/Indian_Masala_Chai.jpg/800px-Indian_Masala_Chai.jpg`,
    aliases: ["aam lassi"], tags: ["drink", "sweet"], dietaryType: "veg", mealType: "drink",
    attribution: "Wikimedia Commons" },
  { name: "Sweet Lassi", cuisine: "punjabi", category: "drink", isVeg: true,
    imageUrl: `${W}/thumb/2/2a/Indian_Masala_Chai.jpg/800px-Indian_Masala_Chai.jpg`,
    aliases: ["meethi lassi"], tags: ["drink"], dietaryType: "veg", mealType: "drink",
    attribution: "Wikimedia Commons" },
  { name: "Nimbu Pani", cuisine: "indian", category: "drink", isVeg: true,
    imageUrl: `${W}/thumb/2/2a/Indian_Masala_Chai.jpg/800px-Indian_Masala_Chai.jpg`,
    aliases: ["lemonade", "shikanji"], tags: ["drink"], dietaryType: "vegan", mealType: "drink",
    attribution: "Wikimedia Commons" },
  { name: "Filter Coffee", cuisine: "south-indian", category: "drink", isVeg: true,
    imageUrl: `${W}/thumb/2/2a/Indian_Masala_Chai.jpg/800px-Indian_Masala_Chai.jpg`,
    aliases: ["kaapi", "south indian coffee"], tags: ["drink"], dietaryType: "veg", mealType: "drink",
    attribution: "Wikimedia Commons" },
  { name: "Gulab Jamun", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/8/85/Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG/800px-Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG`,
    aliases: ["jamun"], tags: ["dessert", "sweet", "popular"], dietaryType: "veg", mealType: "dessert",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Rasgulla", cuisine: "bengali", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/8/85/Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG/800px-Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG`,
    aliases: ["roshogolla"], tags: ["dessert", "bengali"], dietaryType: "veg", mealType: "dessert",
    attribution: "Wikimedia Commons" },
  { name: "Rasmalai", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/8/85/Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG/800px-Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG`,
    aliases: ["ras malai"], tags: ["dessert", "creamy"], dietaryType: "veg", mealType: "dessert",
    attribution: "Wikimedia Commons" },
  { name: "Kheer", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/8/85/Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG/800px-Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG`,
    aliases: ["rice pudding", "payasam"], tags: ["dessert"], dietaryType: "veg", mealType: "dessert",
    attribution: "Wikimedia Commons" },
  { name: "Jalebi", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/8/85/Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG/800px-Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG`,
    aliases: ["jilbi"], tags: ["dessert", "fried"], dietaryType: "veg", mealType: "dessert",
    attribution: "Wikimedia Commons" },
  { name: "Kulfi", cuisine: "indian", category: "dessert", isVeg: true,
    imageUrl: `${W}/thumb/8/85/Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG/800px-Gulab_Jamun_%28Gits%29_Indian_sweet_-_2.JPG`,
    aliases: ["indian ice cream"], tags: ["dessert", "frozen"], dietaryType: "veg", mealType: "dessert",
    attribution: "Wikimedia Commons" },
  { name: "Pani Puri", cuisine: "indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["golgappa", "puchka"], tags: ["snack", "street", "popular"], spiceLevel: 2, dietaryType: "vegan", mealType: "snack",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Bhel Puri", cuisine: "indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["bhelpuri"], tags: ["snack", "street"], dietaryType: "vegan", mealType: "snack",
    attribution: "Wikimedia Commons" },
  { name: "Vada Pav", cuisine: "maharashtrian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["vada pao"], tags: ["snack", "street"], spiceLevel: 2, dietaryType: "veg", mealType: "snack",
    attribution: "Wikimedia Commons" },
  { name: "Pav Bhaji", cuisine: "maharashtrian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["bhaji pav"], tags: ["snack", "popular"], spiceLevel: 2, dietaryType: "veg", mealType: "snack",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Misal Pav", cuisine: "maharashtrian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["misal"], tags: ["snack", "spicy"], spiceLevel: 3, dietaryType: "veg", mealType: "snack",
    attribution: "Wikimedia Commons" },
  { name: "Aloo Tikki", cuisine: "north-indian", category: "snack", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["potato cutlet"], tags: ["snack"], dietaryType: "vegan", mealType: "snack",
    attribution: "Wikimedia Commons" },
  { name: "Veg Manchurian", cuisine: "indo-chinese", category: "starter", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["manchurian"], tags: ["indo-chinese", "starter"], spiceLevel: 2, dietaryType: "veg", mealType: "starter",
    attribution: "Wikimedia Commons" },
  { name: "Chilli Paneer", cuisine: "indo-chinese", category: "starter", isVeg: true,
    imageUrl: `${W}/thumb/3/30/Paneer_Tikka_at_Velleeswarar_Sannathi_Restaurant%2C_Chennai.jpg/800px-Paneer_Tikka_at_Velleeswarar_Sannathi_Restaurant%2C_Chennai.jpg`,
    aliases: ["chilli paneer dry"], tags: ["indo-chinese", "starter"], spiceLevel: 2, dietaryType: "veg", mealType: "starter",
    attribution: "Wikimedia Commons" },
  { name: "Hakka Noodles", cuisine: "indo-chinese", category: "main", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["veg noodles"], tags: ["indo-chinese", "noodles"], dietaryType: "veg", mealType: "main",
    attribution: "Wikimedia Commons" },
  { name: "Schezwan Fried Rice", cuisine: "indo-chinese", category: "rice", isVeg: true,
    imageUrl: `${W}/thumb/9/97/Chicken_Biryani.jpg/800px-Chicken_Biryani.jpg`,
    aliases: ["szechuan fried rice"], tags: ["indo-chinese", "rice"], spiceLevel: 3, dietaryType: "veg", mealType: "rice",
    attribution: "Wikimedia Commons" },
  { name: "Chicken Lollipop", cuisine: "indo-chinese", category: "starter", isVeg: false,
    imageUrl: `${W}/thumb/3/30/Paneer_Tikka_at_Velleeswarar_Sannathi_Restaurant%2C_Chennai.jpg/800px-Paneer_Tikka_at_Velleeswarar_Sannathi_Restaurant%2C_Chennai.jpg`,
    aliases: ["lollipop"], tags: ["indo-chinese", "starter"], spiceLevel: 2, dietaryType: "non-veg", mealType: "starter",
    attribution: "Wikimedia Commons" },
  { name: "Idli", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["idly"], tags: ["breakfast", "steamed"], dietaryType: "vegan", mealType: "breakfast",
    isFeatured: true, attribution: "Wikimedia Commons" },
  { name: "Medu Vada", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["vada", "ulundu vada"], tags: ["breakfast", "fried"], dietaryType: "vegan", mealType: "breakfast",
    attribution: "Wikimedia Commons" },
  { name: "Upma", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["rava upma"], tags: ["breakfast"], dietaryType: "veg", mealType: "breakfast",
    attribution: "Wikimedia Commons" },
  { name: "Pongal", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["khara pongal", "ven pongal"], tags: ["breakfast"], dietaryType: "veg", mealType: "breakfast",
    attribution: "Wikimedia Commons" },
  { name: "Uttapam", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["uttappam"], tags: ["breakfast"], dietaryType: "veg", mealType: "breakfast",
    attribution: "Wikimedia Commons" },
  { name: "Rava Dosa", cuisine: "south-indian", category: "breakfast", isVeg: true,
    imageUrl: `${W}/thumb/c/c6/Idli_Sambar.JPG/800px-Idli_Sambar.JPG`,
    aliases: ["semolina dosa"], tags: ["breakfast", "crispy"], dietaryType: "vegan", mealType: "breakfast",
    attribution: "Wikimedia Commons" },
];
