import { Router, type IRouter } from "express";
import { authenticate } from "../middleware/authenticate";
import healthRouter from "./health";
import authRouter from "./auth";
import publicRouter from "./public";
import tenantsRouter from "./tenants";
import restaurantsRouter from "./restaurants";
import usersRouter from "./users";
import rolesRouter from "./roles";
import tablesRouter from "./tables";
import menuRouter from "./menu";
import menuAiRouter from "./menu-ai";
import kitchensRouter from "./kitchens";
import ordersRouter from "./orders";
import inventoryRouter from "./inventory";
import shiftsRouter from "./shifts";
import leavesRouter from "./leaves";
import staffRouter from "./staff";
import salaryRouter from "./salary";
import payrollRouter from "./payroll";
import customersRouter from "./customers";
import dashboardRouter from "./dashboard";
import branchesRouter from "./branches";
import expensesRouter from "./expenses";
import storageRouter, { publicStorageRouter } from "./storage";
import paymentsRouter from "./payments";
import cashRegisterRouter from "./cash-register";
import deliveryRouter from "./delivery";
import waiterRequestsRouter from "./waiter-requests";
import realtimeRouter from "./realtime";
import subscriptionsRouter, { createStripeWebhookRouter, createCashfreeWebhookRouter } from "./subscriptions";
import billingRouter, { createRazorpayWebhookRouter } from "./billing";
import settingsRouter from "./settings";
import marketingRouter, { marketingAdminRouter } from "./marketing";
import onboardingRouter from "./onboarding";
import adminBroadcastsRouter from "./admin-broadcasts";
import adminSmsRouter from "./admin-sms";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(publicRouter);
router.use(marketingRouter);
router.use(marketingAdminRouter);
router.use(publicStorageRouter);
router.use(realtimeRouter);
router.use(createStripeWebhookRouter());
router.use(createCashfreeWebhookRouter());
router.use(createRazorpayWebhookRouter());

router.use(authenticate);

router.use(tenantsRouter);
router.use(restaurantsRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(tablesRouter);
router.use(menuRouter);
router.use(menuAiRouter);
router.use(kitchensRouter);
router.use(ordersRouter);
router.use(inventoryRouter);
router.use(shiftsRouter);
router.use(leavesRouter);
router.use(staffRouter);
router.use(salaryRouter);
router.use(payrollRouter);
router.use(customersRouter);
router.use(dashboardRouter);
router.use(branchesRouter);
router.use(expensesRouter);
router.use(storageRouter);
router.use(paymentsRouter);
router.use(cashRegisterRouter);
router.use(deliveryRouter);
router.use(waiterRequestsRouter);
router.use(subscriptionsRouter);
router.use(billingRouter);
router.use(settingsRouter);
router.use(onboardingRouter);
router.use(adminBroadcastsRouter);
router.use(adminSmsRouter);

export default router;
