import { Router, type IRouter } from "express";
import { authenticate } from "../middleware/authenticate";
import healthRouter from "./health";
import authRouter from "./auth";
import publicRouter from "./public";
import tenantsRouter from "./tenants";
import restaurantsRouter from "./restaurants";
import usersRouter from "./users";
import rolesRouter from "./roles";
import tablesRouter from "./tables";
import menuRouter from "./menu";
import menuAiRouter from "./menu-ai";
import khanaAiRouter from "./khana-ai";
import khanaAiOpsRouter from "./khana-ai-ops";
import khanaAiUpsellRouter, { publicUpsellRouter } from "./khana-ai-upsell";
import aiSalesInsightsRouter from "./ai-sales-insights";
import reviewsRouter from "./reviews";
import menuImportsRouter from "./menu-imports";
import kitchensRouter from "./kitchens";
import ordersRouter from "./orders";
import voiceOrdersRouter from "./voice-orders";
import inventoryRouter from "./inventory";
import shiftsRouter from "./shifts";
import leavesRouter from "./leaves";
import staffRouter from "./staff";
import salaryRouter from "./salary";
import payrollRouter from "./payroll";
import customersRouter from "./customers";
import dashboardRouter from "./dashboard";
import branchesRouter from "./branches";
import expensesRouter from "./expenses";
import wasteRouter from "./waste";
import storageRouter, { publicStorageRouter } from "./storage";
import paymentsRouter from "./payments";
import cashRegisterRouter from "./cash-register";
import deliveryRouter from "./delivery";
import waiterRequestsRouter from "./waiter-requests";
import realtimeRouter from "./realtime";
import subscriptionsRouter, { createStripeWebhookRouter, createCashfreeWebhookRouter } from "./subscriptions";
import billingRouter, { createRazorpayWebhookRouter } from "./billing";
import couponsRouter from "./coupons";
import settingsRouter from "./settings";
import marketingRouter, { marketingAdminRouter } from "./marketing";
import onboardingRouter from "./onboarding";
import setupWizardRouter from "./setup-wizard";
import adminBroadcastsRouter from "./admin-broadcasts";
import adminSmsRouter from "./admin-sms";
import supportTicketsRouter from "./support-tickets";
import systemHealthRouter from "./system-health";
import apiManagementRouter from "./api-management";
import publicV1Router from "./public-v1";
import adminEmailRouter from "./admin-email";
import maintenanceRouter from "./maintenance";
import adminSettingsRouter, { publicAppSettingsRouter } from "./admin-settings";
import { maintenanceMode, maintenanceGate } from "../middleware/maintenanceMode";
import whatsappRouter, { whatsappPublicRouter } from "./whatsapp";
import auditLogsRouter from "./audit-logs";
import adminAiRouter from "./admin-ai";
import adminAiCreditsRouter from "./admin-ai-credits";
import aiRechargeRouter from "./ai-recharge";
import fraudAlertsRouter from "./fraud-alerts";
import managerOtpRouter from "./manager-otp";
import discountInsightsRouter from "./discount-insights";
import menuPricingRouter from "./menu-pricing";
import pricingRulesRouter from "./pricing-rules";
import dashboardChatRouter from "./dashboard-chat";
import growthEngineRouter from "./growth-engine";
import addonsRouter from "./addons";
import adminAddonsRouter from "./admin-addons";
import fintechRouter from "./fintech";
import documentsRouter from "./documents";
import devicesRouter from "./devices";
import healthScoresRouter from "./health-scores";
import tokensRouter from "./tokens";
import sopTrainingRouter from "./sop-training";
import complianceRouter from "./compliance";
import eventsRouter from "./events";
import aggregatorPayoutsRouter from "./aggregator-payouts";
import accountingRouter from "./accounting";
import foodCourtRouter from "./food-court";
import bakeryRouter, { bakeryPublicRouter } from "./bakery";
import mealPlansRouter from "./meal-plans";
import hotelRouter from "./hotel";
import sustainabilityRouter from "./sustainability";
import tiffinRouter from "./tiffin";
import cloudKitchenRouter from "./cloud-kitchen";
import portalRouter from "./portal";

const router: IRouter = Router();

router.use(healthRouter);
router.use(maintenanceGate);
router.use(authRouter);
router.use(publicRouter);
router.use(publicUpsellRouter);
router.use(marketingRouter);
router.use(marketingAdminRouter);
router.use(publicStorageRouter);
router.use(publicAppSettingsRouter);
router.use(realtimeRouter);
router.use(createStripeWebhookRouter());
router.use(createCashfreeWebhookRouter());
router.use(createRazorpayWebhookRouter());
router.use(whatsappPublicRouter);
router.use(tokensRouter);
router.use(bakeryPublicRouter);

// Public API namespace (api-key authenticated). Mounted BEFORE the JWT
// `authenticate` gate so external clients can call it with `Bearer <api_key>`.
router.use(publicV1Router);

router.use(authenticate);
router.use(maintenanceMode);

router.use(adminSettingsRouter);
router.use(tenantsRouter);
router.use(restaurantsRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(tablesRouter);
router.use(menuRouter);
router.use(menuAiRouter);
router.use(khanaAiRouter);
router.use(dashboardChatRouter);
router.use(khanaAiOpsRouter);
router.use(khanaAiUpsellRouter);
router.use(aiSalesInsightsRouter);
router.use(reviewsRouter);
router.use(menuImportsRouter);
router.use(kitchensRouter);
router.use(ordersRouter);
router.use(voiceOrdersRouter);
router.use(inventoryRouter);
router.use(shiftsRouter);
router.use(leavesRouter);
router.use(staffRouter);
router.use(salaryRouter);
router.use(payrollRouter);
router.use(customersRouter);
router.use(dashboardRouter);
router.use(branchesRouter);
router.use(expensesRouter);
router.use(wasteRouter);
router.use(storageRouter);
router.use(paymentsRouter);
router.use(cashRegisterRouter);
router.use(deliveryRouter);
router.use(waiterRequestsRouter);
router.use(subscriptionsRouter);
router.use(billingRouter);
router.use(couponsRouter);
router.use(settingsRouter);
router.use(onboardingRouter);
router.use(setupWizardRouter);
router.use(adminBroadcastsRouter);
router.use(adminSmsRouter);
router.use(supportTicketsRouter);
router.use(systemHealthRouter);
router.use(apiManagementRouter);
router.use(adminEmailRouter);
router.use(maintenanceRouter);
router.use(whatsappRouter);
router.use(auditLogsRouter);
router.use(adminAiRouter);
router.use(adminAiCreditsRouter);
router.use(aiRechargeRouter);
router.use(fraudAlertsRouter);
router.use(managerOtpRouter);
router.use(discountInsightsRouter);
router.use(menuPricingRouter);
router.use(pricingRulesRouter);
router.use(growthEngineRouter);
router.use(addonsRouter);
router.use(adminAddonsRouter);
router.use(fintechRouter);
router.use(documentsRouter);
router.use(devicesRouter);
router.use(healthScoresRouter);
router.use(sopTrainingRouter);
router.use(complianceRouter);
router.use(eventsRouter);
router.use(aggregatorPayoutsRouter);
router.use(accountingRouter);
router.use(foodCourtRouter);
router.use(bakeryRouter);
router.use(mealPlansRouter);
router.use(hotelRouter);
router.use(sustainabilityRouter);
router.use(tiffinRouter);
router.use(cloudKitchenRouter);
router.use(portalRouter);

export default router;
