import { Router, type IRouter } from "express";
import { authenticate } from "../middleware/authenticate";
import healthRouter from "./health";
import authRouter from "./auth";
import publicRouter from "./public";
import tenantsRouter from "./tenants";
import restaurantsRouter from "./restaurants";
import usersRouter from "./users";
import rolesRouter from "./roles";
import tablesRouter from "./tables";
import menuRouter from "./menu";
import menuAiRouter from "./menu-ai";
import kitchensRouter from "./kitchens";
import ordersRouter from "./orders";
import inventoryRouter from "./inventory";
import shiftsRouter from "./shifts";
import leavesRouter from "./leaves";
import staffRouter from "./staff";
import salaryRouter from "./salary";
import payrollRouter from "./payroll";
import customersRouter from "./customers";
import dashboardRouter from "./dashboard";
import branchesRouter from "./branches";
import expensesRouter from "./expenses";
import storageRouter, { publicStorageRouter } from "./storage";
import paymentsRouter from "./payments";
import cashRegisterRouter from "./cash-register";
import deliveryRouter from "./delivery";
import waiterRequestsRouter from "./waiter-requests";
import realtimeRouter from "./realtime";
import subscriptionsRouter, { createStripeWebhookRouter, createCashfreeWebhookRouter } from "./subscriptions";
import billingRouter, { createRazorpayWebhookRouter } from "./billing";
import couponsRouter from "./coupons";
import settingsRouter from "./settings";
import marketingRouter, { marketingAdminRouter } from "./marketing";
import onboardingRouter from "./onboarding";
import adminBroadcastsRouter from "./admin-broadcasts";
import adminSmsRouter from "./admin-sms";
import supportTicketsRouter from "./support-tickets";
import systemHealthRouter from "./system-health";
import apiManagementRouter from "./api-management";
import publicV1Router from "./public-v1";
import adminEmailRouter from "./admin-email";
import maintenanceRouter from "./maintenance";
import adminSettingsRouter, { publicAppSettingsRouter } from "./admin-settings";
import { maintenanceMode, maintenanceGate } from "../middleware/maintenanceMode";
import whatsappRouter, { whatsappPublicRouter } from "./whatsapp";
import auditLogsRouter from "./audit-logs";
import adminAiRouter from "./admin-ai";
import adminAiCreditsRouter from "./admin-ai-credits";
import aiRechargeRouter from "./ai-recharge";

const router: IRouter = Router();

router.use(healthRouter);
router.use(maintenanceGate);
router.use(authRouter);
router.use(publicRouter);
router.use(marketingRouter);
router.use(marketingAdminRouter);
router.use(publicStorageRouter);
router.use(publicAppSettingsRouter);
router.use(realtimeRouter);
router.use(createStripeWebhookRouter());
router.use(createCashfreeWebhookRouter());
router.use(createRazorpayWebhookRouter());
router.use(whatsappPublicRouter);

// Public API namespace (api-key authenticated). Mounted BEFORE the JWT
// `authenticate` gate so external clients can call it with `Bearer <api_key>`.
router.use(publicV1Router);

router.use(authenticate);
router.use(maintenanceMode);

router.use(adminSettingsRouter);
router.use(tenantsRouter);
router.use(restaurantsRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(tablesRouter);
router.use(menuRouter);
router.use(menuAiRouter);
router.use(kitchensRouter);
router.use(ordersRouter);
router.use(inventoryRouter);
router.use(shiftsRouter);
router.use(leavesRouter);
router.use(staffRouter);
router.use(salaryRouter);
router.use(payrollRouter);
router.use(customersRouter);
router.use(dashboardRouter);
router.use(branchesRouter);
router.use(expensesRouter);
router.use(storageRouter);
router.use(paymentsRouter);
router.use(cashRegisterRouter);
router.use(deliveryRouter);
router.use(waiterRequestsRouter);
router.use(subscriptionsRouter);
router.use(billingRouter);
router.use(couponsRouter);
router.use(settingsRouter);
router.use(onboardingRouter);
router.use(adminBroadcastsRouter);
router.use(adminSmsRouter);
router.use(supportTicketsRouter);
router.use(systemHealthRouter);
router.use(apiManagementRouter);
router.use(adminEmailRouter);
router.use(maintenanceRouter);
router.use(whatsappRouter);
router.use(auditLogsRouter);
router.use(adminAiRouter);
router.use(adminAiCreditsRouter);
router.use(aiRechargeRouter);

export default router;
