import { pgTable, text, serial, timestamp, integer, boolean, decimal, jsonb, uniqueIndex, index } from "drizzle-orm/pg-core";
import { tenantsTable } from "./tenants";
import { restaurantsTable } from "./restaurants";
import { usersTable } from "./users";

export const aiProvidersTable = pgTable("ai_providers", {
  id: serial("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  kind: text("kind").notNull(),
  isEnabled: boolean("is_enabled").notNull().default(false),
  apiKeyCipher: text("api_key_cipher"),
  apiKeyIv: text("api_key_iv"),
  apiKeyTag: text("api_key_tag"),
  apiKeyMasked: text("api_key_masked"),
  baseUrl: text("base_url"),
  orgId: text("org_id"),
  defaultModel: text("default_model"),
  backupModel: text("backup_model"),
  timeoutMs: integer("timeout_ms").notNull().default(60000),
  maxTokens: integer("max_tokens").notNull().default(4096),
  temperature: decimal("temperature", { precision: 4, scale: 2 }).notNull().default("0.70"),
  notes: text("notes"),
  status: text("status").notNull().default("inactive"),
  lastTestedAt: timestamp("last_tested_at"),
  lastTestStatus: text("last_test_status"),
  lastTestLatencyMs: integer("last_test_latency_ms"),
  lastTestError: text("last_test_error"),
  config: jsonb("config").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const aiProviderModelsTable = pgTable("ai_provider_models", {
  id: serial("id").primaryKey(),
  providerId: integer("provider_id").notNull().references(() => aiProvidersTable.id, { onDelete: "cascade" }),
  model: text("model").notNull(),
  label: text("label"),
  modality: text("modality").notNull().default("text"),
  contextWindow: integer("context_window"),
  inputCostPer1k: decimal("input_cost_per_1k", { precision: 10, scale: 6 }),
  outputCostPer1k: decimal("output_cost_per_1k", { precision: 10, scale: 6 }),
  imageCostPerCall: decimal("image_cost_per_call", { precision: 10, scale: 6 }),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (t) => ({
  uniqProviderModel: uniqueIndex("ai_provider_models_provider_model_idx").on(t.providerId, t.model),
}));

export const aiFeatureModelAssignmentsTable = pgTable("ai_feature_model_assignments", {
  id: serial("id").primaryKey(),
  featureSlug: text("feature_slug").notNull().unique(),
  featureLabel: text("feature_label").notNull(),
  category: text("category").notNull().default("general"),
  modality: text("modality").notNull().default("text"),
  primaryProviderId: integer("primary_provider_id").references(() => aiProvidersTable.id, { onDelete: "set null" }),
  primaryModel: text("primary_model"),
  fallbackProviderId: integer("fallback_provider_id").references(() => aiProvidersTable.id, { onDelete: "set null" }),
  fallbackModel: text("fallback_model"),
  temperature: decimal("temperature", { precision: 4, scale: 2 }).notNull().default("0.70"),
  maxTokens: integer("max_tokens").notNull().default(2048),
  systemPrompt: text("system_prompt"),
  promptTemplateId: integer("prompt_template_id"),
  jsonMode: boolean("json_mode").notNull().default(false),
  visionEnabled: boolean("vision_enabled").notNull().default(false),
  imageGenEnabled: boolean("image_gen_enabled").notNull().default(false),
  isEnabled: boolean("is_enabled").notNull().default(true),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const aiPromptTemplatesTable = pgTable("ai_prompt_templates", {
  id: serial("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  featureSlug: text("feature_slug"),
  outputFormat: text("output_format").notNull().default("text"),
  variables: jsonb("variables").$type<string[]>().notNull().default([]),
  jsonSchema: jsonb("json_schema").$type<Record<string, unknown> | null>(),
  activeVersion: integer("active_version").notNull().default(1),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const aiPromptTemplateVersionsTable = pgTable("ai_prompt_template_versions", {
  id: serial("id").primaryKey(),
  templateId: integer("template_id").notNull().references(() => aiPromptTemplatesTable.id, { onDelete: "cascade" }),
  version: integer("version").notNull(),
  systemPrompt: text("system_prompt"),
  userTemplate: text("user_template").notNull(),
  notes: text("notes"),
  createdBy: integer("created_by").references(() => usersTable.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (t) => ({
  uniqTemplateVersion: uniqueIndex("ai_prompt_template_versions_idx").on(t.templateId, t.version),
}));

export const aiSafetySettingsTable = pgTable("ai_safety_settings", {
  id: serial("id").primaryKey(),
  requireApprovalReviewReplies: boolean("require_approval_review_replies").notNull().default(false),
  requireApprovalCampaigns: boolean("require_approval_campaigns").notNull().default(true),
  requireApprovalMenuImport: boolean("require_approval_menu_import").notNull().default(true),
  blockAbuse: boolean("block_abuse").notNull().default(true),
  blockHealthClaims: boolean("block_health_claims").notNull().default(true),
  blockDefamation: boolean("block_defamation").notNull().default(true),
  maxRetries: integer("max_retries").notNull().default(2),
  rateLimitPerMinute: integer("rate_limit_per_minute").notNull().default(60),
  rateLimitPerDayPerRestaurant: integer("rate_limit_per_day_per_restaurant").notNull().default(2000),
  dataPrivacyNotice: text("data_privacy_notice"),
  storePrompt: boolean("store_prompt").notNull().default(true),
  storeResponse: boolean("store_response").notNull().default(true),
  bannedPhrases: jsonb("banned_phrases").$type<string[]>().notNull().default([]),
  updatedBy: integer("updated_by").references(() => usersTable.id, { onDelete: "set null" }),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const aiRequestLogsTable = pgTable("ai_request_logs", {
  id: serial("id").primaryKey(),
  featureSlug: text("feature_slug").notNull(),
  providerId: integer("provider_id").references(() => aiProvidersTable.id, { onDelete: "set null" }),
  providerSlug: text("provider_slug"),
  model: text("model"),
  modality: text("modality").notNull().default("text"),
  status: text("status").notNull(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  tenantId: integer("tenant_id").references(() => tenantsTable.id, { onDelete: "set null" }),
  restaurantId: integer("restaurant_id").references(() => restaurantsTable.id, { onDelete: "set null" }),
  userId: integer("user_id").references(() => usersTable.id, { onDelete: "set null" }),
  inputTokens: integer("input_tokens").notNull().default(0),
  outputTokens: integer("output_tokens").notNull().default(0),
  totalTokens: integer("total_tokens").notNull().default(0),
  latencyMs: integer("latency_ms"),
  retries: integer("retries").notNull().default(0),
  fallbackUsed: boolean("fallback_used").notNull().default(false),
  costUsd: decimal("cost_usd", { precision: 12, scale: 6 }).notNull().default("0"),
  creditsUsed: integer("credits_used").notNull().default(0),
  promptSnapshot: text("prompt_snapshot"),
  responseSnapshot: text("response_snapshot"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (t) => ({
  byFeature: index("ai_request_logs_feature_idx").on(t.featureSlug, t.createdAt),
  byProvider: index("ai_request_logs_provider_idx").on(t.providerId, t.createdAt),
  byRestaurant: index("ai_request_logs_restaurant_idx").on(t.restaurantId, t.createdAt),
  byCreated: index("ai_request_logs_created_idx").on(t.createdAt),
}));
